<?php
/**
 * See LICENSE.md for license details.
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Netresearch\ShippingUi\ViewModel\Rma\CustomerLabel $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php foreach ($viewModel->getPNGDocuments() as $document): ?>
    <div class="box box-qr">
        <strong class="box-title">
            <span><?= $escaper->escapeHtml($document->getTitle()) ?></span>
        </strong>
        <div class="box-actions">
            <a class="action" href="data:image/png;base64,<?= /* @noEscape */ base64_encode($document->getLabelData()) ?>"
               download="<?= $escaper->escapeHtmlAttr($viewModel->getFileName($document)) ?>">
                <?= $escaper->escapeHtml(__('Download %1', $document->getTitle())) ?>
            </a>
        </div>
        <div class="box-content">
            <a href="data:image/png;base64,<?= /* @noEscape */ base64_encode($document->getLabelData()) ?>"
               download="<?= $escaper->escapeHtmlAttr($viewModel->getFileName($document)) ?>">
                <img src="data:image/png;base64,<?= /* @noEscape */ base64_encode($document->getLabelData()) ?>" alt="<?= $escaper->escapeHtml($document->getTitle()) ?>"/>
            </a>
        </div>
    </div>
<?php endforeach; ?>
