<?php
/**
 * See LICENSE.md for license details.
 */
?>

<?php
/** @var \Netresearch\ShippingUi\Block\AdditionalFee\Total $block */
/** @var \Netresearch\ShippingUi\ViewModel\Order\Totals\AdditionalFee $viewModel */
$viewModel = $block->getViewModel();
$source = $block->getParentBlock()->getSource();
?>
<?php if ($viewModel->displayBoth($source)): ?>
    <tr class="row-totals">
        <td <?= /* @noEscape */ $block->getData('label_properties') ?> scope="row">
            <?= $escaper->escapeHtml($viewModel->getLabel($source)) ?> <?= $escaper->escapeHtml(__('(Excl. Tax)')) ?>
        </td>
        <td <?= /* @noEscape */ $block->getData('value_properties') ?>>
            <?= $escaper->escapeHtml($viewModel->getPriceExclTax($source), ['span']) ?>
        </td>
    </tr>
    <tr class="row-totals">
        <td <?= /* @noEscape */ $block->getData('label_properties') ?> scope="row">
            <?= $escaper->escapeHtml($viewModel->getLabel($source)) ?> <?= $escaper->escapeHtml(__('(Incl. Tax)')) ?>
        </td>
        <td <?= /* @noEscape */ $block->getData('value_properties') ?>>
            <?= $escaper->escapeHtml($viewModel->getPriceInclTax($source), ['span']) ?>
        </td>
    </tr>
<?php elseif ($viewModel->displayIncludeTax($source)): ?>
    <tr>
        <td <?= /* @noEscape */ $block->getData('label_properties') ?> scope="row">
            <?= $escaper->escapeHtml($viewModel->getLabel($source)) ?>
        </td>
        <td <?= /* @noEscape */ $block->getData('value_properties') ?>>
            <?= $escaper->escapeHtml($viewModel->getPriceInclTax($source), ['span']) ?>
        </td>
    </tr>
<?php else: ?>
    <tr class="row-totals">
        <td <?= /* @noEscape */ $block->getData('label_properties') ?> scope="row">
            <?= $escaper->escapeHtml($viewModel->getLabel($source)) ?>
        </td>
        <td <?= /* @noEscape */ $block->getData('value_properties') ?>>
            <?= $escaper->escapeHtml($viewModel->getPriceExclTax($source), ['span']) ?>
        </td>
    </tr>
<?php endif; ?>
