<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Netresearch\ShippingUi\ViewModel\Order\Info\DeliveryLocation $locationViewModel */
/** @var \Netresearch\ShippingUi\ViewModel\Order\Info\ServiceSelection $selectionViewModel */
$locationViewModel = $block->getData('locationViewModel');
$selectionViewModel = $block->getData('selectionViewModel');

$orderId = $selectionViewModel->getOrder()->getId();

$services = $selectionViewModel->getValues($orderId);
$deliveryAddressLines = $locationViewModel->getAddressLines($orderId);
?>
<?php if (!empty($services)): ?>
    <section class="nrshipping-selected-services">
        <div class="section-title">
            <span class="title"><?= $block->escapeHtml(__('Shipping Services')) ?></span>
        </div>
        <div class="section-content">
            <div class="section-item">
                <table class="data-table">
                    <tbody>
                    <?php foreach ($services as $idx => $service) : ?>
                        <tr class="col-<?= /* @noEscape */ (int) $idx ?>">
                            <td class="label"><?= $block->escapeHtml($service['label']) ?></td>
                            <td><?= $block->escapeHtml($service['value']) ?></td>
                        </tr>
                    <?php endforeach; ?>

                    <?php if (!empty($deliveryAddressLines)) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Location Address')) ?></th>
                        <td>
                            <?php foreach ($deliveryAddressLines as $addressLine) : ?>
                                <div><?= $block->escapeHtml($addressLine) ?></div>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endif; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </section>
<?php endif; ?>
