<?php
/**
 * See LICENSE.md for license details.
 */

/** @var \Magento\Backend\Block\Template $block */
/** @var \Netresearch\ShippingCore\Api\Data\RecipientStreetInterface $recipientStreet */
$recipientStreet = $block->getData('recipient_street');
$orderId = $block->getData('order_id');

/** @var \Netresearch\ShippingUi\ViewModel\Order\Info\RecipientStreet $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php if ($recipientStreet): ?>
    <section class="admin__page-section order-addresses nrshipping-recipient-address">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $escaper->escapeHtml(__('Recipient Street')) ?></span>
                    <div class="actions">
                        <?= /* @noEscape */ $viewModel->getRecipientStreetEditLink($recipientStreet, $orderId); ?>
                    </div>
                </div>
                <div class="admin__page-section-item-content nrshipping-recipient-street">
                    <dl>
                        <dt class="label"><?= $escaper->escapeHtml(__('Street Name')) ?></dt>
                        <dd class="values"><?= $escaper->escapeHtml($recipientStreet->getName()) ?></dd>
                        <dt class="label"><?= $escaper->escapeHtml(__('Street Number')) ?></dt>
                        <dd class="values"><?= $escaper->escapeHtml($recipientStreet->getNumber()) ?></dd>
                        <dt class="label"><?= $escaper->escapeHtml(__('Supplement')) ?></dt>
                        <dd class="values"><?= $escaper->escapeHtml($recipientStreet->getSupplement()) ?></dd>
                    </dl>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
