<?php

/**
 * See LICENSE.md for license details.
 */

declare(strict_types=1);
/** @var \Magento\Backend\Block\Template $block */
/** @var Netresearch\ShippingUi\ViewModel\Order\Packaging\Popup $viewModel */
$viewModel = $block->getData('popup_view_model');
?>
<div id="packaging-content" class="nrshipping-packaging-popup" data-bind="scope: 'nrshipping-packaging-popup'">
    <script type="text/x-magento-init">
    {
        "#packaging-content": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "nrshipping-packaging-popup": {
                        "component": "Netresearch_ShippingUi/js/packaging/controller",
                        "config": {
                            "shippingSettings": <?= /* @noEscape */ json_encode($viewModel->getShippingSettings()) ?>,
                            "submitUrl": "<?= $block->escapeUrl($viewModel->getSubmitUrl()) ?>",
                            "successRedirect": "<?= $block->escapeUrl($viewModel->getSuccessRedirectUrl()) ?>"
                        }
                    }
                }
            }
        }
    }
    </script>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
