<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Netresearch\ShippingUi\ViewModel\Order\Info\DeliveryLocation $locationViewModel */
/** @var \Netresearch\ShippingUi\ViewModel\Order\Info\ServiceSelection $selectionViewModel */
$locationViewModel = $block->getData('locationViewModel');
$selectionViewModel = $block->getData('selectionViewModel');

$orderId = (int) $this->getData('order_id');

$services = $orderId ? $selectionViewModel->getValues($orderId) : [];
$deliveryAddressLines = $locationViewModel->getAddressLines($orderId);
?>
<?php if (!empty($services)): ?>
    <table class="order-details nrshipping-selected-services">
        <tr>
            <td class="address-details">
                <h3><?= $block->escapeHtml(__('Shipping Services')) ?></h3>
                <table class="order-information-table">
                    <tbody>
                    <?php foreach ($services as $service) : ?>
                        <tr>
                            <th><?= $block->escapeHtml($service['label']) ?></th>
                            <td style="padding: 0 0 0 10px"><?= $block->escapeHtml($service['value']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php if (!empty($deliveryAddressLines)): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Location Address')) ?></th>
                            <td>
                                <?php foreach ($deliveryAddressLines as $addressLine) : ?>
                                    <div><?= $block->escapeHtml($addressLine) ?></div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </td>
        </tr>
    </table>
<?php endif; ?>
